#!/bin/zsh

# make sure developer tools are installed 
echo "install xcode developer tools"
xcode-select --install

# brew installs
echo
echo "Start Brewing"

# Check for Homebrew, install if we don't have it
if test ! $(which brew); then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# update homebrew
brew update
PACKAGES=(
	coreutils
	getantibody/tap/antibody
	bat
	diff-so-fancy
	exa
	fd
	gcc
	howdoi
	httpie
	mas
	nmap
	ripgrep
	ruby
	telnet
	tig
	neofetch
)
CASKS=(
    flux
		hyper
		visual-studio-code
		alfred
		spotify
		tower
		focus
		postman
		slack
		docker
		evernote
)
echo "Installing packages..."
brew install ${PACKAGES[@]}
echo "Installing cask..."
brew tap phinze/homebrew-cask
echo "Installing cask apps..."
brew cask install ${CASKS[@]}

NPM_PACKAGES=(
	pure-prompt
)
echo
echo "Install NPM packages"
npm install --global ${NPM_PACKAGES[@]}

echo
echo "Clean up Brew and NPM"
source ~/.brew-clean

# bootstrap config files
echo
echo "install the .files and config files"
echo "also install vscode plugins"
./install

# Oh My Zsh
echo
echo "Install Oh My Zsh"
$ sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo
echo "source zsh and update plugins"
source ~/.zshrc
updateplugins

echo
echo "Installing Vim Plugins"
vim +PlugInstall --sync +qa

echo
echo "install cursive fonts"
cd ~
git clone https://github.com/kencrocken/FiraCodeiScript
mv FiraCodeiScript/*.ttf ~/Library/Fonts/.
rm -rf FiraCodeiScript
cd Dotfiles

echo
echo "You might have to install python3"

echo
echo "default shell to zsh"
sudo chsh -s /bin/zsh

echo
echo
echo "Bootstrapping complete"
echo "Please restart system"
